Update autotools use
rrthomas/enchant pull request #23
Opened 2016-12-18 19:34 UTC by rrthomas

This gets rid of autogen.sh: autoreconf is used instead

2016-12-18 19:51 UTC, hfiguiere requested changes
Thanks for catching these documentation issues. 

But `autogen.sh` must stay. It is expected by things like OStree, etc. It is also the reason why TravisCI failed (but that could be fixed)

2016-12-18 19:51 UTC, rrthomas commented
No problem, it can be reduced to one line, to call `autoreconf`. I shall update the PR.

2016-12-18 20:35 UTC, hfiguiere commented
it is expected thar `autogen.sh` runs configure unless `NOCONFIGURE=1` env is set. Therefor there shouldn't be any need to change the `travis.yml` file. Also I think you should squash a few of these commits together.

2016-12-18 20:39 UTC, rrthomas commented
I noticed that it was trying to run `make` without first running `./configure`. But I didn't set `NOCONFIGURE`.

Anyway, I will get it working first, then I will squash commits, then I will try again changing the script back to what it was originally. Thanks!

2016-12-18 21:11 UTC, TingPing commented
A reasonable autogen.sh is something like:

```sh
#!/bin/sh
# Run this to generate all the initial makefiles, etc.

srcdir=`dirname $0`
test -z "$srcdir" && srcdir=.

(test -f $srcdir/configure.ac) || {
	echo -n "**Error**: Directory "\`$srcdir\'" does not look like the top-level directory"
	exit 1
}

aclocal --install -I m4 || exit 1
autoreconf --install -Wno-portability || exit 1

if [ "$NOCONFIGURE" = "" ]; then
        $srcdir/configure "$@" || exit 1

        if [ "$1" = "--help" ]; then exit 0 else
                echo "Now type \`make\' to compile" || exit 1
        fi
else
        echo "Skipping configure process."
fi

set +x
```

2016-12-18 21:16 UTC, rrthomas commented
What's wrong with just running `autoreconf -i`?

2016-12-18 21:22 UTC, rrthomas commented
As far as I can see, it is up to `autogen.sh` to provide the `NOCONFIGURE` logic. The old script did not; it had a `--no-configure` command-line flag instead.

Hence, I've used @TingPing's suggestion.

2016-12-18 21:48 UTC, rrthomas commented
All looks good now, let me know if there's anything else.

By the way, I'll need to update the libtool versioning scheme in my `enchant-2-0` branch, because the current scheme doesn't work when the major number is incremented and the minor reset to 0.

2016-12-18 21:48 UTC, hfiguiere commented
It was an old autogen.sh that had not been updated recently. @TingPing suggestion is the right one

Part of the rationale is that we can run `autogen.sh` from a `builddir` that is not `srcdir`. This is also expected.

2016-12-18 22:37 UTC, hfiguiere requested changes

2016-12-18 22:37 UTC, hfiguiere commented on Makefile.am
> +ACLOCAL_AMFLAGS = -I m4
I think that what you are looking for is `ac-helpers`. Not sure how up to date it is, and I think it is fine to rename it to `m4`.

2016-12-18 22:37 UTC, hfiguiere commented on Makefile.am
> -	autogen.sh	\
You need to keep this. autogen.sh must be in the dist.

2016-12-18 22:37 UTC, hfiguiere commented on configure.ac
> +AC_CONFIG_MACRO_DIR([m4])
see my comment above about how there is `ac-helpers`

2016-12-18 22:55 UTC, rrthomas commented
Good catch about `EXTRA_DIST`! Thanks for the note about `ac-helpers`.

2016-12-20 04:13 UTC, hfiguiere approved these changes

2016-12-20 04:14 UTC, merged